agg_interval: 3
agg_steps: 3
claims_to_sample: 400
communities:
- 12
- 127
- 1
- 72
- 28
- 43
community_graph_path: ../../data/community_net.gexf
depths:
- 2
- 4
- 6
fact_checks_per_step: 5
high_belief: 0.55
high_impactedness: 0.8
learning_rate: 0.2
load_data: true
low_belief: 0.45
low_impactedness: 0.3
min_degree: 1
nodes_to_sample: 5
num_claims: 900
num_topics: 4
output_sim_final_intervention_kc: ../output/simulation_final_intervention_kc_label_stratified_sample_topic_mitigation
output_sim_final_intervention_random: ../output/simulation_final_intervention_random_label_random_sample_standard_mitigation
output_sim_final_intervention_stratified: ../output/simulation_final_intervention_stratified_label
output_sim_final_no_intervention: ../output/simulation_final_no_intervention
output_sim_midpoint: ../output/simulation_pre_period
perc_bots: 0.1
perc_nodes_to_subset: 0.005
post_duration: 2
random_communities: true
raw_network_path: ../../data/nodes_with_community.gpickle
ready_network_path: ../output/simulation_net_communities_3_43_56.gpickle
runtime: 50
sample_method: stratified_nodes_visited
update_beliefs: true
