agg_interval: 3
agg_steps: 3
claims_to_sample: 500
communities:
- 49
- 43
- 127
- 120
community_graph_path: ../../data/community_net.gexf
depths:
- 2
- 4
- 6
fact_checks_per_step: 20
high_belief: 0.55
high_impactedness: 0.8
learning_rate: 0.2
load_data: true
low_belief: 0.45
low_impactedness: 0.3
min_degree: 5
nodes_to_sample: 100
num_claims: 9000
output_sim_final_no_intervention: ../output/simulation_final_no_intervention
output_sim_midpoint: ../output/simulation_pre_period
perc_bots: 0.1
perc_nodes_to_subset: 0.1
post_duration: 3
random_communities: true
raw_network_path: ../../data/nodes_with_community.gpickle
ready_network_path: ../output/simulation_net_communities_55_56_49.gpickle
runtime: 100
update_beliefs: true
