reps: 10
agg_interval: 3
agg_steps: 3
claims_to_sample: 1000
# if running state 2, the ordering should be (1) majority (2) minority (3) knowledgeable community
# if running state 1, the ordering should be (1) majority, then order doesn't matter for minority communities
communities:
- 3
- 49
- 72
# machine learning feature parameter
depths:
- 2
- 4
- 6
fact_checks_per_step: 20
high_belief: 
- 0.7
- 0.7
low_belief: 
- 0.4
- 0.3
learning_rate: 0.2
load_data: False
low_impactedness: 
- 0.3
- 0.2
high_impactedness: 
- 0.8
- 0.8
middle_impactedness: 0.5
min_degree: 1
nodes_to_sample: 30
num_claims: 10000
perc_bots: 0.1
perc_nodes_to_subset: 0.25
post_duration: 3
random_communities: False
runtime: 150
update_beliefs: true
state_of_world: 2
output_sim_final_no_intervention: ../output/simulation_final_no_intervention
output_sim_midpoint: ../output/simulation_pre_period
raw_network_path: ../../data/nodes_with_community.gexf
ready_network_path: ../output/simulation_net_communities_3_43_56.gpickle
community_graph_path: ../../data/community_net.gexf
